import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-blue-700">Next.JS app</h1>
        <p>This a test to make sure it's working!</p>
        <p>And now we've got automatic GIT deployments!</p>
        <p>Another change to check automatic updates 😁</p>
      </main>
    </>
  );
}
