import Head from "next/head";
import Link from "next/link";
import Nav from "../components/nav";
import Image from "next/image";
import { useEffect, useState } from "react";

export default function Home() {
  const [adjective, setAdjective] = useState("");

  useEffect(() => {
    // Fetch adjective from Next.js api
    fetch("api/adjective")
      .then((res) => res.json())
      .then((data) => {
        setAdjective(data.adjective);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className="bg-gray-600 h-screen">
        <div className="max-w-screen-sm mx-auto py-20 text-center text-gray-400">
          <h1 className="font-bold text-2xl mb-4 text-gray-300">Home</h1>
          <p className="mb-2">Welcome to this cool Next.js app.</p>
          <p className="mb-8">Here's a picture of my cat.</p>
          <Image
            src="/cat.jpg"
            alt="cat"
            width={600}
            height={400}
            className="rounded-xl mb-8"
          />
          <p className="text-xl">
            She is very <span className="font-bold">{adjective}</span>!
          </p>
        </div>
      </main>
    </>
  );
}
